#!/bin/sh

# This is a wrapper script for Mapserver
# It's been adapted from:
#     http://mapserver.org/cgi/wrapper.html

MAPSERV="/usr/lib/cgi-bin/mapserv"
MS_MAPFILE="/home/geo2/gisficheiros/geoland2_aux.map" exec ${MAPSERV}
